# Generated by Django 3.1.3 on 2020-11-21 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_asset_assettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assettype',
            name='spec',
            field=models.CharField(default=django.utils.timezone.now, max_length=245),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
