# Generated by Django 3.1.3 on 2020-11-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201121_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='date',
        ),
        migrations.RemoveField(
            model_name='assettype',
            name='spec',
        ),
    ]
