# Generated by Django 3.1.3 on 2020-11-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201121_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
    ]
